Repository hiero-ledger/governance, pull requests merged in 2025-05, with the labels that each got.

#271 chore: Delete elections/nominees/mar-2025-election/Roger-Barker.md
  elections/nominees/mar-2025-election/Roger-Barker.md
Labels: Audit

#276 Chore: Add rules exception instructions and tracker
  project-rules-exceptions.md
  roles-and-groups.md
Labels: documentation

#282 chore: Update project-rules-exceptions.md
  project-rules-exceptions.md
Labels: documentation

#285 chore: Update config.yaml to add maintainers groups to governance (triage)
  config.yaml
Labels: maintainer-vote

#283 chore: Move Tim Farber-Newman
  config.yaml
Labels: maintainer-vote

#297 chore: Remove user cody-littley from assigned teams
  config.yaml
Labels: Audit
