Repository hiero-ledger/governance, pull requests merged in 2025-04, with the labels that each got.

#204 chore: update repo-properties.yaml
  repo-properties.yaml
Labels: documentation

#205 chore: update repo-properties for hiero-sdk-java
  repo-properties.yaml
Labels: documentation

#224 chore: Update config.yaml to add solo-admins team
  config.yaml
Labels: enhancement

#228 chore: Add PR templates to governance repository
  .github/PULL_REQUEST_TEMPLATE/custom_properties_update_pr_template.md
  .github/PULL_REQUEST_TEMPLATE/new_repository_pr_template.md
  .github/PULL_REQUEST_TEMPLATE/new_team_pr_template.md
  .github/PULL_REQUEST_TEMPLATE/vote_pr_template.md
Labels: documentation, enhancement

#231 chore: Add selector info for PR templates
  .github/PULL_REQUEST_TEMPLATE/custom_properties_update_pr_template.md
  .github/PULL_REQUEST_TEMPLATE/new_repository_pr_template.md
  .github/PULL_REQUEST_TEMPLATE/new_team_pr_template.md
  .github/PULL_REQUEST_TEMPLATE/vote_pr_template.md
Labels: documentation, enhancement

#239 chore: add custom property workflows and files
  .github/properties_schema.json
  .github/workflows/configure-custom-properties.yaml
  .github/workflows/read-all-custom-properties.yaml
  .github/workflows/update-custom-properties.yaml
  repo-properties.yaml
Labels: documentation, enhancement

#245 chore: Update workflows
  .github/workflows/configure-custom-properties.yaml
  .github/workflows/read-all-custom-properties.yaml
  .github/workflows/update-custom-properties.yaml
Labels: enhancement
